[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "helloworld"
path = "src/helloworld.rs"

[dependencies]
fhirbolt = {version = "0.4.0", features = ["r5"]}
rand = "0.8.5"
